# Use root/example as user/password credentials
version: '3.1'
name: qblock

services:

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    entrypoint: ["/usr/bin/mongod","--bind_ip_all","--replSet","rs0"]

  mongosetup:
    build: ./mongosetup
    container_name: mongosetup
    networks:
      - mongo-network
    depends_on:
      - mongodb
    restart: on-failure
    environment:
      WAIT_HOSTS: mongodb:27017

  core:
    build:
      context: ./
      dockerfile: ./core/Dockerfile
    container_name: core
    networks:
      - mongo-network
    depends_on:
      - mongosetup
    environment:
      WAIT_HOSTS: mongodb:27017

  client:
    build: ./client
    container_name: client
    networks:
      - mongo-network
    depends_on:
      - mongosetup
    ports:
      - "23614:23614"
    environment:
      WAIT_HOSTS: mongodb:27017

  miner:
    build:
      context: ./
      dockerfile: ./miner/Dockerfile
    container_name: miner
    networks:
      - mongo-network
    depends_on:
      - mongosetup
    environment:
      WAIT_HOSTS: mongodb:27017

networks:
  mongo-network:
    driver: bridge